apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: facturation-api
spec:
  selector:
    matchLabels:
      app: facturation-api
  template:
    metadata:
      labels:
        app: facturation-api
    spec:
      containers:
      - name: api-container
        image: fredericeducentre/facturation-api:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DB_HOST
            value: database-service
          - name: DB_USER
            value: user
          - name: DB_PASSWORD
            value: password
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: facturation-front
spec:
  selector:
    matchLabels:
      app: facturation-front
  template:
    metadata:
      labels:
        app: facturation-front
    spec:
      containers:
      - name: front-container
        image: fredericeducentre/facturation-front:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: facturation-database
spec:
  selector:
    matchLabels:
      app: facturation-database
  template:
    metadata:
      labels:
        app: facturation-database
    spec:
      containers:
      - name: database-container
        image: mysql:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: database-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort  
  selector:
    app: facturation-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort  
  selector:
    app: facturation-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: NodePort  
  selector:
    app: facturation-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: database-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
